# Generated by Django 3.2.9 on 2021-12-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.CharField(default='rating', max_length=255),
            preserve_default=False,
        ),
    ]
