# Generated by Django 3.2.9 on 2021-12-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spotlight',
            new_name='Welcome',
        ),
    ]
