# Generated by Django 3.2.9 on 2021-12-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_whyus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhyUs',
        ),
    ]
