# Generated by Django 3.2.9 on 2022-01-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
